/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metalabsgui;


import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author rhysbryn
 */
public class LoginGUI extends javax.swing.JFrame {

    static int x = 0;
    static Timer timer;
    /**
     * Creates new form RealLoginGUI
     */
    public LoginGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label2 = new javax.swing.JLabel();
        TxtField1 = new javax.swing.JTextField();
        Label3 = new javax.swing.JLabel();
        PassField1 = new javax.swing.JPasswordField();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 48, 56));

        Label2.setBackground(new java.awt.Color(255, 255, 255));
        Label2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Label2.setForeground(new java.awt.Color(255, 255, 255));
        Label2.setText("Username:");

        TxtField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TxtField1.setBorder(null);

        Label3.setBackground(new java.awt.Color(255, 255, 255));
        Label3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Label3.setForeground(new java.awt.Color(255, 255, 255));
        Label3.setText("Password:");

        PassField1.setBorder(null);

        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/STUDENT LOGIN.gif"))); // NOI18N
        Button1.setBorder(null);
        Button1.setBorderPainted(false);
        Button1.setContentAreaFilled(false);
        Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Button1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button1MouseReleased(evt);
            }
        });

        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/ADMIN LOGIN.gif"))); // NOI18N
        Button2.setBorder(null);
        Button2.setBorderPainted(false);
        Button2.setContentAreaFilled(false);
        Button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Button2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button2MouseReleased(evt);
            }
        });
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/Small METALABS LOGO 1 Loop.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label2)
                    .addComponent(TxtField1)
                    .addComponent(Label3)
                    .addComponent(PassField1))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("loginFrame");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed

    }//GEN-LAST:event_Button2ActionPerformed

    private void Button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseEntered
        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/ADMIN LOGIN(SELECTED).png")));
    }//GEN-LAST:event_Button2MouseEntered

    private void Button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseExited
        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/ADMIN LOGIN.gif")));
    }//GEN-LAST:event_Button2MouseExited

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseEntered
        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/STUDENT LOGIN(SELECTED).png")));
    }//GEN-LAST:event_Button1MouseEntered

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseExited
        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/STUDENT LOGIN.gif")));
    }//GEN-LAST:event_Button1MouseExited

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
       
    }//GEN-LAST:event_Button2MouseClicked

    private void Button2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MousePressed
        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/ADMIN LOGIN(CLICKED).png")));
    }//GEN-LAST:event_Button2MousePressed

    private void Button2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseReleased
        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/ADMIN LOGIN(SELECTED).png")));
    }//GEN-LAST:event_Button2MouseReleased

    private void Button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MousePressed
         Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/STUDENT LOGIN(CLICKED).png")));
    }//GEN-LAST:event_Button1MousePressed

    private void Button1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseReleased
         Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalabsgui/STUDENT LOGIN(SELECTED).png")));
    }//GEN-LAST:event_Button1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      FlatDarkLaf.setup();
      
        
      timer = new Timer(45,new ActionListener() {
          
          @Override
          public void actionPerformed(ActionEvent e){
          
              Label2.setForeground(new Color(255,255,255,x++));
              TxtField1.setBackground(new Color(0,0,0,x++));
              PassField1.setBackground(new Color(0,0,0,x++));
              Label3.setForeground(new Color(255,255,255,x++));
              Button2.setBackground(new Color(255,255,255,x++));
              Button1.setBackground(new Color(255,255,255,x++));
              
              if (x == 255){
                  timer.stop();
              }
          }
          
      });
      
      
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new metalabsgui.splashscreen.SplashScreen(null, true).setVisible(true);
                timer.start();
                new LoginGUI().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Button1;
    public static javax.swing.JButton Button2;
    public static javax.swing.JLabel Label2;
    public static javax.swing.JLabel Label3;
    public static javax.swing.JPasswordField PassField1;
    public static javax.swing.JTextField TxtField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
